setTimeout(()=>{
    document.getElementById('callb').innerHTML=10;
    setTimeout(()=>{
        document.getElementById('callb').innerHTML=9;
        setTimeout(()=>{
            document.getElementById('callb').innerHTML=8;
            setTimeout(()=>{
                document.getElementById('callb').innerHTML=7;
                setTimeout(()=>{
                    document.getElementById('callb').innerHTML=6;
                    setTimeout(()=>{
                        document.getElementById('callb').innerHTML=5;
                        setTimeout(()=>{
                            document.getElementById('callb').innerHTML=4;
                            setTimeout(()=>{
                                document.getElementById('callb').innerHTML=3;
                                setTimeout(()=>{
                                    document.getElementById('callb').innerHTML=2;
                                    setTimeout(()=>{
                                        document.getElementById('callb').innerHTML=1;
                                        setTimeout(()=>{
                                            document.getElementById('callb').innerHTML="Happy Independence Day";
                                        },1000)
                                     },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)